const express = require('express')
const {authenticationMiddleware} = require('../middleware/auth')
const router = express.Router()
const {registerUser, loginUser, getAllUsers, getUserById, updateUser, deleteUser,topContributors,isBookmarked,saveResource,removeSavedResource,removeContributedResource, getSavedResources,getContributedResources,logoutUser, googleAuth} = require('../controllers/userController')

// router.post('/register',registerUser)
// router.post('/login',loginUser)
router.get('/logout',authenticationMiddleware,logoutUser)
router.get('/getParticularUser',authenticationMiddleware,getUserById).put('/updateUser',authenticationMiddleware,updateUser)
router.delete('/deleteUser',authenticationMiddleware,deleteUser)
router.get('/topContributors',authenticationMiddleware,topContributors)
router.get('/isBookmarked/:id',authenticationMiddleware,isBookmarked)
router.post('/saveResource/:id',authenticationMiddleware,saveResource)
router.delete('/removeSavedResource/:id',authenticationMiddleware,removeSavedResource)
router.delete('/removeContributedResource/:id',authenticationMiddleware,removeContributedResource)
router.get('/getSavedResources',authenticationMiddleware,getSavedResources)
router.get('/getContributedResources',authenticationMiddleware,getContributedResources)
router.post('/google-login',googleAuth)
module.exports = router